//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPGIS1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\Iddeal_Server_Ver8\Iddeal_DE1\Data\Comp_BP_Data_Lasalle.mdb;Persist Security Info=True;Password=waiheke;User ID=developer;Jet OLEDB:System database=C:\Iddeal_Server_Ver8\V08.mdw;Jet OLEDB:Database Password=waiheke")]
        public string CompWorksConnectionString {
            get {
                return ((string)(this["CompWorksConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\Iddeal_Server_Ver8\Iddeal_DE1\Data\Comp_SW_Data_Lasalle_GIS.mdb;Persist Security Info=True;Password=waiheke;User ID=developer;Jet OLEDB:System database=C:\Iddeal_Server_Ver8\V08.mdw;Jet OLEDB:Database Password=waiheke")]
        public string CompWorks_SW_Data_Connection {
            get {
                return ((string)(this["CompWorks_SW_Data_Connection"]));
            }
        }
    }
}
